/*
 * Copyright (c) Business Thinking Ltd. 2019-2023
 * This software includes code developed by the dbtvault Team at Business Thinking Ltd. Trading as Datavault
 */

{%- macro prepend_generated_by() -%}

    {{- adapter.dispatch('prepend_generated_by', 'dbtvault')() -}}

{%- endmacro %}

{%- macro default__prepend_generated_by() -%}
-- Generated by ColeyDev/dbtvault. Default.
{%- endmacro -%}

{%- macro redshift__prepend_generated_by() -%}
-- Generated by ColeyDev/dbtvault. Redshift.
{%- endmacro -%}